services:
  app:
    build: .
    container_name: app
    volumes:
      - .:/mini-karina:cached
      - ~/.ssh:/root/.ssh
      - ~/.bash_history:/root/.bash_history
      - bundle_cache:/bundle_cache
      - mini-karina-modules:/mini-karina-modules
    command: sh -c

volumes:
  bundle_cache:
  mini-karina-modules: